# Generated by Django 4.1.7 on 2024-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255, null=True)),
                ('album_url', models.CharField(max_length=255, null=True)),
                ('artist_name', models.CharField(max_length=255, null=True)),
                ('image_url', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
                ('x_coord', models.IntegerField(default=1)),
                ('y_coord', models.IntegerField(default=1)),
                ('color', models.CharField(default='130, 128, 131', max_length=128)),
                ('date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
