# Generated by Django 4.1.7 on 2024-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='x_mult',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fly',
            name='y_mult',
            field=models.IntegerField(default=1),
        ),
    ]
