# Generated by Django 4.1.7 on 2024-02-02 12:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_alter_fly_x_mult_alter_fly_y_mult'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('time', models.TimeField()),
                ('x_coord', models.IntegerField(null=True)),
                ('y_coord', models.IntegerField(null=True)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.fly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.user')),
            ],
        ),
    ]
