# Generated by Django 4.1.7 on 2024-02-02 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0005_alter_play_finish_time_alter_play_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
