# Generated by Django 4.1.7 on 2024-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0006_alter_play_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='x_coord',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='play',
            name='y_coord',
            field=models.IntegerField(default=1),
        ),
    ]
