# Generated by Django 4.1.7 on 2024-02-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0007_alter_play_x_coord_alter_play_y_coord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='x_coord',
        ),
        migrations.RemoveField(
            model_name='play',
            name='y_coord',
        ),
        migrations.AddField(
            model_name='play',
            name='x_mult',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='play',
            name='y_mult',
            field=models.FloatField(default=1),
        ),
    ]
