# Generated by Django 4.1.7 on 2024-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0008_remove_play_x_coord_remove_play_y_coord_play_x_mult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='x_mult',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fly',
            name='y_mult',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='play',
            name='x_mult',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='play',
            name='y_mult',
            field=models.FloatField(default=0),
        ),
    ]
