# Generated by Django 4.1.7 on 2024-02-03 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0009_alter_fly_x_mult_alter_fly_y_mult_alter_play_x_mult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='pathm',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
