# Generated by Django 4.1.7 on 2024-02-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0011_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
