# Generated by Django 4.1.7 on 2024-02-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0012_play_created_play_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fly',
            name='artwork_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
