# Generated by Django 4.1.7 on 2024-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0013_remove_fly_image_url_fly_artwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='fly_color',
            field=models.CharField(default='#FFFFF', max_length=128),
        ),
    ]
