# Generated by Django 4.1.7 on 2024-02-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0014_fly_fly_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='album_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
