# Generated by Django 4.1.7 on 2024-02-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0015_fly_album_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
