# Generated by Django 4.1.7 on 2024-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0016_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='fly_color',
            field=models.CharField(default='#FFFFFF', max_length=128),
        ),
    ]
