# Generated by Django 4.1.7 on 2024-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0017_alter_fly_fly_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
