# Generated by Django 4.1.7 on 2024-02-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0018_fly_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='date',
        ),
        migrations.RemoveField(
            model_name='play',
            name='fly',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('fly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spot.fly')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.day'),
        ),
    ]
