# Generated by Django 4.1.7 on 2024-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0019_remove_fly_date_remove_play_fly_day_play_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
