# Generated by Django 4.1.7 on 2024-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0020_fly_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
