# Generated by Django 4.1.7 on 2024-02-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0021_fly_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='image',
        ),
    ]
