# Generated by Django 5.2.17 on 2026-09-12 12:33

import utils.encrypted_fields
from django.db import migrations


def encrypt_existing_tokens(apps, schema_editor):
    Studio = apps.get_model('spot', 'Studio')
    for studio in Studio.objects.exclude(token_info__in=[None, '']).iterator():
        studio.save(update_fields=['token_info'])


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0023_play_give_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='token_info',
            field=utils.encrypted_fields.EncryptedTokenField(null=True),
        ),
        migrations.RunPython(encrypt_existing_tokens, migrations.RunPython.noop),
    ]
