# Generated by Django 2.2.3 on 2019-07-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sessionID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
