# Generated by Django 2.2.3 on 2019-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_users_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sessionID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
