# Generated by Django 2.2.3 on 2019-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_auto_20190710_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
