# Generated by Django 2.2.3 on 2019-07-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20190710_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='started',
            field=models.BooleanField(null=True),
        ),
    ]
