# Generated by Django 2.2.3 on 2019-07-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20190710_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='partyID',
            new_name='party',
        ),
    ]
