# Generated by Django 2.2.3 on 2019-07-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_auto_20190713_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='title',
            new_name='name',
        ),
    ]
