# Generated by Django 2.2.3 on 2019-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0011_auto_20190714_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.AddField(
            model_name='users',
            name='hasPicked',
            field=models.BooleanField(default=False),
        ),
    ]
