# Generated by Django 2.2.3 on 2019-07-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0012_auto_20190714_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.Users'),
        ),
    ]
