# Generated by Django 2.2.3 on 2019-07-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0014_auto_20190719_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
