# Generated by Django 2.2.3 on 2019-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0015_auto_20190720_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
