# Generated by Django 2.2.3 on 2019-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0016_party_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='username',
        ),
        migrations.AddField(
            model_name='party',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
