# Generated by Django 2.2.3 on 2019-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0017_auto_20190727_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
