# Generated by Django 2.2.3 on 2019-07-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0018_party_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='token',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
