# Generated by Django 2.2.3 on 2019-07-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0019_party_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='deviceID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deviceID', models.CharField(max_length=200)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
        ),
    ]
