# Generated by Django 2.2.3 on 2019-08-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0022_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='url_open',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='token',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
