# Generated by Django 2.2.3 on 2019-08-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0023_auto_20190802_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
    ]
