# Generated by Django 2.2.3 on 2019-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0025_remove_songs_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='songs',
            name='state',
            field=models.CharField(default='not_played', max_length=10),
        ),
    ]
