# Generated by Django 2.2.3 on 2019-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0026_auto_20190803_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='startTime',
            field=models.FloatField(default=0),
        ),
    ]
