# Generated by Django 2.2.3 on 2019-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0027_songs_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='time',
            field=models.IntegerField(default=90),
        ),
    ]
