# Generated by Django 2.2.3 on 2019-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0028_auto_20190908_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='joinCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
