# Generated by Django 2.2.3 on 2019-10-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0029_party_joincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
