# Generated by Django 2.2.6 on 2019-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0030_library_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='url_open',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
