# Generated by Django 2.2.6 on 2019-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0031_auto_20191020_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hasLiked',
            field=models.BooleanField(default=False),
        ),
    ]
