# Generated by Django 2.2.6 on 2019-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0032_users_hasliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='time',
            field=models.IntegerField(default=80),
        ),
    ]
