# Generated by Django 2.2.6 on 2019-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0033_auto_20191025_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
