# Generated by Django 2.2.6 on 2019-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0035_auto_20191026_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='debug',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
