# Generated by Django 2.2.6 on 2019-11-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0038_auto_20191116_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='token_info',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
