# Generated by Django 2.2.6 on 2019-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0040_party_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
