# Generated by Django 3.0.4 on 2020-03-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0042_auto_20200322_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
