# Generated by Django 3.0.4 on 2020-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0043_songs_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
