# Generated by Django 3.0.4 on 2020-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0046_category_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='hasSkip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='isHost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
