# Generated by Django 3.0.4 on 2020-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0047_auto_20200627_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='refreshRate',
            field=models.IntegerField(default=5),
        ),
    ]
