# Generated by Django 3.0.4 on 2020-07-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0049_auto_20200628_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='thread',
            field=models.BooleanField(default=False),
        ),
    ]
