# Generated by Django 3.0.4 on 2020-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0050_party_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
