# Generated by Django 3.0.4 on 2020-07-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0051_party_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
