# Generated by Django 3.0.4 on 2020-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0054_auto_20200712_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='display',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
