# Generated by Django 3.0.4 on 2020-07-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0056_auto_20200712_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='structure',
            field=models.CharField(choices=[('{} in the Title', '{} in the Title'), ('Songs that {}', 'Songs that {}'), ('Songs where {}', 'Songs where {}'), ('{} Songs', '{} Songs'), ('Songs with {}', 'Songs with {}'), ('Songs from {}', 'Songs from {}'), ('Songs by {}', 'Songs by {}'), ('Songs {}', 'Songs {}'), ('Songs about {}', 'Songs about {}'), ('{}', '{}')], default='{}', max_length=64),
        ),
    ]
