# Generated by Django 3.0.8 on 2020-07-18 11:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0058_party_device_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='lib_repo',
            field=django_mysql.models.SetTextField(models.CharField(max_length=32), null=True, size=None),
        ),
    ]
