# Generated by Django 3.0.8 on 2020-07-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0061_party_current_lib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='current_lib',
            new_name='indicies',
        ),
    ]
