# Generated by Django 3.0.8 on 2021-03-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0065_auto_20200830_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='roundTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='state',
            field=models.CharField(default='assign', max_length=30),
        ),
        migrations.AlterField(
            model_name='songs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='turn',
            field=models.CharField(default='not_picked', max_length=20),
        ),
    ]
