# Generated by Django 3.0.8 on 2021-03-27 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0066_auto_20210314_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Library'),
        ),
    ]
