# Generated by Django 3.2 on 2021-06-05 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0068_auto_20210501_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
