# Generated by Django 3.2 on 2022-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0070_auto_20210605_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='color',
            field=models.CharField(default='255,255,255', max_length=128),
        ),
    ]
