# Generated by Django 3.2 on 2022-09-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0071_songs_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='color',
            field=models.CharField(default='', max_length=128),
        ),
    ]
