# Generated by Django 3.2 on 2022-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0072_alter_songs_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='color',
            field=models.CharField(default='255,255,255', max_length=128),
        ),
    ]
