# Generated by Django 3.2 on 2022-10-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0073_alter_songs_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='artist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='artist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
