# Generated by Django 3.2.16 on 2022-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0075_alter_songs_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='color',
            field=models.CharField(default='0, 0, 0', max_length=128),
        ),
    ]
