# Generated by Django 3.2.16 on 2022-11-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0077_alter_songs_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
