# Generated by Django 4.1.3 on 2022-12-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0078_library_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
