# Generated by Django 5.2.17 on 2026-09-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0079_users_icon'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('joinCode__isnull', False)), fields=('joinCode',), name='unique_active_party_join_code'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('sessionID__isnull', False)), fields=('party', 'sessionID'), name='unique_active_party_session'),
        ),
    ]
