# Generated by Django 5.2.17 on 2026-09-12 12:33

import utils.encrypted_fields
from django.db import migrations
from django.db.models import Q


def encrypt_existing_tokens(apps, schema_editor):
    Party = apps.get_model('party', 'Party')
    populated = Party.objects.filter(
        ~Q(token__in=[None, '']) | ~Q(token_info__in=[None, ''])
    )
    for party in populated.iterator():
        party.save(update_fields=['token', 'token_info'])


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0080_party_unique_active_party_join_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='token',
            field=utils.encrypted_fields.EncryptedTokenField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='token_info',
            field=utils.encrypted_fields.EncryptedTokenField(null=True),
        ),
        migrations.RunPython(encrypt_existing_tokens, migrations.RunPython.noop),
    ]
